export const OPENINGS = [
  'Remember that God is here.',
  'Be still before the Lord.',
  'Rest in His presence.',
  'Come without hurry.',
  'You already have His attention.',
  'Receive His love before you say a word.',
  'Let your heart become quiet.',
  'Christ welcomes you.',
  'Lay every distraction before Him.',
  'Draw near with confidence.',
  'His steadfast love surrounds you.',
  'The Father delights to hear you.',
  'Pause and remember His faithfulness.',
  'Rest beneath His care.',
  'Lift your eyes to Christ.',
  'Entrust these moments to Him.',
  'The Good Shepherd is with you.',
  'Let His Word quiet your heart.',
  'He is nearer than you realize.',
  'Begin by resting in His love.'
];

export const REFLECTIONS = [
  'What does this reveal about God?',
  'What does this teach you about His love?',
  'What part of God\'s character shines here?',
  'Where do you see His faithfulness?',
  'What beauty of God stands out?',
  'What invitation is God giving you?',
  'What truth about Him is easy to forget?',
  'What promise do you see?',
  'How does this reveal His care?',
  'What does this show about His heart?',
  'What does this teach about His mercy?',
  'What does this reveal about His goodness?',
  'What comfort is found here?',
  'What hope is offered here?',
  'How does this display His patience?',
  'What does this passage celebrate about God?',
  'What attribute of God is most evident?',
  'What would God have you notice here?',
  'Where do you see His gentleness?',
  'How is His wisdom displayed?',
  'What truth deserves lingering over?',
  'What phrase invites your attention?',
  'What would it look like to believe this today?',
  'Which word speaks most deeply to you?',
  'What truth can you carry with you?',
  'What does this stir you to praise?',
  'What goodness of God is on display?',
  'What assurance is found here?',
  'What does this reveal about His presence?',
  'Stay with this truth for a few moments.'
];

export const CHRIST = [
  'What does this reveal about Christ?',
  'How does this passage point to Jesus?',
  'What beauty of Christ is seen here?',
  'How does Christ fulfill this truth?',
  'What does this teach about the heart of Jesus?',
  'How does Christ care for His people here?',
  'What does this reveal about His love?',
  'How do you see the Good Shepherd?',
  'What does this teach about Christ\'s faithfulness?',
  'How has Christ fulfilled this promise?',
  'What invitation from Jesus do you hear?',
  'How does this deepen your love for Christ?',
  'What aspect of Christ\'s character is displayed?',
  'How does this help you trust Him?',
  'What comfort do you find in Christ here?',
  'How has Jesus made this promise yours?',
  'What does this awaken in your worship of Christ?',
  'What does this show about the Savior\'s heart?',
  'What does this remind you of about Jesus?',
  'Rest in Christ for a few moments.'
];

export const CLOSINGS = [
  'Rest in His love.',
  'Carry this truth with you today.',
  'Walk in His peace.',
  'Continue speaking with Him.',
  'Remember His faithfulness.',
  'Let His Word remain in you.',
  'Return to this truth throughout the day.',
  'Go in the strength He provides.',
  'Remain in His care.',
  'Trust Him with what lies ahead.',
  'Rest beneath His grace.',
  'Let His love steady your heart.',
  'Keep your eyes on Christ.',
  'Return to Him often today.',
  'Receive His peace.',
  'Walk in quiet confidence.',
  'Remember that He is with you.',
  'Leave your burdens with Him.',
  'Abide in His love.',
  'Go in peace.'
];